services:
  - type: web
    name: moon-store-api
    runtime: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm run migrate && npm run seed && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: ALLOWED_ORIGINS
        sync: false
