/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as CustomerDisplayRouteImport } from './routes/customer-display'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/_admin'
import { Route as AuthenticatedBarcodeRouteImport } from './routes/_authenticated/barcode'
import { Route as AuthenticatedDeliveriesRouteImport } from './routes/_authenticated/deliveries'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedLayawayRouteImport } from './routes/_authenticated/layaway'
import { Route as AuthenticatedPosRouteImport } from './routes/_authenticated/pos'
import { Route as AuthenticatedRegisterRouteImport } from './routes/_authenticated/register'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated/sales'
import { Route as AuthenticatedShiftsRouteImport } from './routes/_authenticated/shifts'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/_admin/index'
import { Route as AuthenticatedAdminAiInsightsRouteImport } from './routes/_authenticated/_admin/ai-insights'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/_admin/analytics'
import { Route as AuthenticatedAdminAuditLogRouteImport } from './routes/_authenticated/_admin/audit-log'
import { Route as AuthenticatedAdminBackupRouteImport } from './routes/_authenticated/_admin/backup'
import { Route as AuthenticatedAdminBranchesRouteImport } from './routes/_authenticated/_admin/branches'
import { Route as AuthenticatedAdminBundlesRouteImport } from './routes/_authenticated/_admin/bundles'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/_admin/categories'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated/_admin/customers'
import { Route as AuthenticatedAdminDistributorsRouteImport } from './routes/_authenticated/_admin/distributors'
import { Route as AuthenticatedAdminExpensesRouteImport } from './routes/_authenticated/_admin/expenses'
import { Route as AuthenticatedAdminExportsRouteImport } from './routes/_authenticated/_admin/exports'
import { Route as AuthenticatedAdminFeedbackRouteImport } from './routes/_authenticated/_admin/feedback'
import { Route as AuthenticatedAdminGiftCardsRouteImport } from './routes/_authenticated/_admin/gift-cards'
import { Route as AuthenticatedAdminOnlineOrdersRouteImport } from './routes/_authenticated/_admin/online-orders'
import { Route as AuthenticatedAdminPromotionsRouteImport } from './routes/_authenticated/_admin/promotions'
import { Route as AuthenticatedAdminPurchaseOrdersRouteImport } from './routes/_authenticated/_admin/purchase-orders'
import { Route as AuthenticatedAdminReportBuilderRouteImport } from './routes/_authenticated/_admin/report-builder'
import { Route as AuthenticatedAdminSegmentsRouteImport } from './routes/_authenticated/_admin/segments'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/_admin/settings'
import { Route as AuthenticatedAdminSmartPricingRouteImport } from './routes/_authenticated/_admin/smart-pricing'
import { Route as AuthenticatedAdminStockCountRouteImport } from './routes/_authenticated/_admin/stock-count'
import { Route as AuthenticatedAdminStorefrontRouteImport } from './routes/_authenticated/_admin/storefront'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/_admin/users'
import { Route as AuthenticatedAdminVendorsRouteImport } from './routes/_authenticated/_admin/vendors'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerDisplayRoute = CustomerDisplayRouteImport.update({
  id: '/customer-display',
  path: '/customer-display',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBarcodeRoute = AuthenticatedBarcodeRouteImport.update({
  id: '/barcode',
  path: '/barcode',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDeliveriesRoute = AuthenticatedDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLayawayRoute = AuthenticatedLayawayRouteImport.update({
  id: '/layaway',
  path: '/layaway',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPosRoute = AuthenticatedPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRegisterRoute = AuthenticatedRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedShiftsRoute = AuthenticatedShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAiInsightsRoute =
  AuthenticatedAdminAiInsightsRouteImport.update({
    id: '/ai-insights',
    path: '/ai-insights',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditLogRoute =
  AuthenticatedAdminAuditLogRouteImport.update({
    id: '/audit-log',
    path: '/audit-log',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBackupRoute =
  AuthenticatedAdminBackupRouteImport.update({
    id: '/backup',
    path: '/backup',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBranchesRoute =
  AuthenticatedAdminBranchesRouteImport.update({
    id: '/branches',
    path: '/branches',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBundlesRoute =
  AuthenticatedAdminBundlesRouteImport.update({
    id: '/bundles',
    path: '/bundles',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCustomersRoute =
  AuthenticatedAdminCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDistributorsRoute =
  AuthenticatedAdminDistributorsRouteImport.update({
    id: '/distributors',
    path: '/distributors',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminExpensesRoute =
  AuthenticatedAdminExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminExportsRoute =
  AuthenticatedAdminExportsRouteImport.update({
    id: '/exports',
    path: '/exports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFeedbackRoute =
  AuthenticatedAdminFeedbackRouteImport.update({
    id: '/feedback',
    path: '/feedback',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGiftCardsRoute =
  AuthenticatedAdminGiftCardsRouteImport.update({
    id: '/gift-cards',
    path: '/gift-cards',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOnlineOrdersRoute =
  AuthenticatedAdminOnlineOrdersRouteImport.update({
    id: '/online-orders',
    path: '/online-orders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPromotionsRoute =
  AuthenticatedAdminPromotionsRouteImport.update({
    id: '/promotions',
    path: '/promotions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPurchaseOrdersRoute =
  AuthenticatedAdminPurchaseOrdersRouteImport.update({
    id: '/purchase-orders',
    path: '/purchase-orders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReportBuilderRoute =
  AuthenticatedAdminReportBuilderRouteImport.update({
    id: '/report-builder',
    path: '/report-builder',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSegmentsRoute =
  AuthenticatedAdminSegmentsRouteImport.update({
    id: '/segments',
    path: '/segments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSmartPricingRoute =
  AuthenticatedAdminSmartPricingRouteImport.update({
    id: '/smart-pricing',
    path: '/smart-pricing',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStockCountRoute =
  AuthenticatedAdminStockCountRouteImport.update({
    id: '/stock-count',
    path: '/stock-count',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStorefrontRoute =
  AuthenticatedAdminStorefrontRouteImport.update({
    id: '/storefront',
    path: '/storefront',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminVendorsRoute =
  AuthenticatedAdminVendorsRouteImport.update({
    id: '/vendors',
    path: '/vendors',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/': typeof AuthenticatedAdminIndexRoute
  '/customer-display': typeof CustomerDisplayRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/barcode': typeof AuthenticatedBarcodeRoute
  '/deliveries': typeof AuthenticatedDeliveriesRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/layaway': typeof AuthenticatedLayawayRoute
  '/pos': typeof AuthenticatedPosRoute
  '/register': typeof AuthenticatedRegisterRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/shifts': typeof AuthenticatedShiftsRoute
  '/ai-insights': typeof AuthenticatedAdminAiInsightsRoute
  '/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/backup': typeof AuthenticatedAdminBackupRoute
  '/branches': typeof AuthenticatedAdminBranchesRoute
  '/bundles': typeof AuthenticatedAdminBundlesRoute
  '/categories': typeof AuthenticatedAdminCategoriesRoute
  '/customers': typeof AuthenticatedAdminCustomersRoute
  '/distributors': typeof AuthenticatedAdminDistributorsRoute
  '/expenses': typeof AuthenticatedAdminExpensesRoute
  '/exports': typeof AuthenticatedAdminExportsRoute
  '/feedback': typeof AuthenticatedAdminFeedbackRoute
  '/gift-cards': typeof AuthenticatedAdminGiftCardsRoute
  '/online-orders': typeof AuthenticatedAdminOnlineOrdersRoute
  '/promotions': typeof AuthenticatedAdminPromotionsRoute
  '/purchase-orders': typeof AuthenticatedAdminPurchaseOrdersRoute
  '/report-builder': typeof AuthenticatedAdminReportBuilderRoute
  '/segments': typeof AuthenticatedAdminSegmentsRoute
  '/settings': typeof AuthenticatedAdminSettingsRoute
  '/smart-pricing': typeof AuthenticatedAdminSmartPricingRoute
  '/stock-count': typeof AuthenticatedAdminStockCountRoute
  '/storefront': typeof AuthenticatedAdminStorefrontRoute
  '/users': typeof AuthenticatedAdminUsersRoute
  '/vendors': typeof AuthenticatedAdminVendorsRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/': typeof AuthenticatedAdminIndexRoute
  '/customer-display': typeof CustomerDisplayRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/barcode': typeof AuthenticatedBarcodeRoute
  '/deliveries': typeof AuthenticatedDeliveriesRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/layaway': typeof AuthenticatedLayawayRoute
  '/pos': typeof AuthenticatedPosRoute
  '/register': typeof AuthenticatedRegisterRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/shifts': typeof AuthenticatedShiftsRoute
  '/ai-insights': typeof AuthenticatedAdminAiInsightsRoute
  '/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/backup': typeof AuthenticatedAdminBackupRoute
  '/branches': typeof AuthenticatedAdminBranchesRoute
  '/bundles': typeof AuthenticatedAdminBundlesRoute
  '/categories': typeof AuthenticatedAdminCategoriesRoute
  '/customers': typeof AuthenticatedAdminCustomersRoute
  '/distributors': typeof AuthenticatedAdminDistributorsRoute
  '/expenses': typeof AuthenticatedAdminExpensesRoute
  '/exports': typeof AuthenticatedAdminExportsRoute
  '/feedback': typeof AuthenticatedAdminFeedbackRoute
  '/gift-cards': typeof AuthenticatedAdminGiftCardsRoute
  '/online-orders': typeof AuthenticatedAdminOnlineOrdersRoute
  '/promotions': typeof AuthenticatedAdminPromotionsRoute
  '/purchase-orders': typeof AuthenticatedAdminPurchaseOrdersRoute
  '/report-builder': typeof AuthenticatedAdminReportBuilderRoute
  '/segments': typeof AuthenticatedAdminSegmentsRoute
  '/settings': typeof AuthenticatedAdminSettingsRoute
  '/smart-pricing': typeof AuthenticatedAdminSmartPricingRoute
  '/stock-count': typeof AuthenticatedAdminStockCountRoute
  '/storefront': typeof AuthenticatedAdminStorefrontRoute
  '/users': typeof AuthenticatedAdminUsersRoute
  '/vendors': typeof AuthenticatedAdminVendorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/customer-display': typeof CustomerDisplayRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/barcode': typeof AuthenticatedBarcodeRoute
  '/_authenticated/deliveries': typeof AuthenticatedDeliveriesRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/layaway': typeof AuthenticatedLayawayRoute
  '/_authenticated/pos': typeof AuthenticatedPosRoute
  '/_authenticated/register': typeof AuthenticatedRegisterRoute
  '/_authenticated/sales': typeof AuthenticatedSalesRoute
  '/_authenticated/shifts': typeof AuthenticatedShiftsRoute
  '/_authenticated/_admin/ai-insights': typeof AuthenticatedAdminAiInsightsRoute
  '/_authenticated/_admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/_admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/_authenticated/_admin/backup': typeof AuthenticatedAdminBackupRoute
  '/_authenticated/_admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/_authenticated/_admin/bundles': typeof AuthenticatedAdminBundlesRoute
  '/_authenticated/_admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/_admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/_authenticated/_admin/distributors': typeof AuthenticatedAdminDistributorsRoute
  '/_authenticated/_admin/expenses': typeof AuthenticatedAdminExpensesRoute
  '/_authenticated/_admin/exports': typeof AuthenticatedAdminExportsRoute
  '/_authenticated/_admin/feedback': typeof AuthenticatedAdminFeedbackRoute
  '/_authenticated/_admin/gift-cards': typeof AuthenticatedAdminGiftCardsRoute
  '/_authenticated/_admin/online-orders': typeof AuthenticatedAdminOnlineOrdersRoute
  '/_authenticated/_admin/promotions': typeof AuthenticatedAdminPromotionsRoute
  '/_authenticated/_admin/purchase-orders': typeof AuthenticatedAdminPurchaseOrdersRoute
  '/_authenticated/_admin/report-builder': typeof AuthenticatedAdminReportBuilderRoute
  '/_authenticated/_admin/segments': typeof AuthenticatedAdminSegmentsRoute
  '/_authenticated/_admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/_admin/smart-pricing': typeof AuthenticatedAdminSmartPricingRoute
  '/_authenticated/_admin/stock-count': typeof AuthenticatedAdminStockCountRoute
  '/_authenticated/_admin/storefront': typeof AuthenticatedAdminStorefrontRoute
  '/_authenticated/_admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/_admin/vendors': typeof AuthenticatedAdminVendorsRoute
  '/_authenticated/_admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/'
    | '/customer-display'
    | '/locations'
    | '/login'
    | '/barcode'
    | '/deliveries'
    | '/inventory'
    | '/layaway'
    | '/pos'
    | '/register'
    | '/sales'
    | '/shifts'
    | '/ai-insights'
    | '/analytics'
    | '/audit-log'
    | '/backup'
    | '/branches'
    | '/bundles'
    | '/categories'
    | '/customers'
    | '/distributors'
    | '/expenses'
    | '/exports'
    | '/feedback'
    | '/gift-cards'
    | '/online-orders'
    | '/promotions'
    | '/purchase-orders'
    | '/report-builder'
    | '/segments'
    | '/settings'
    | '/smart-pricing'
    | '/stock-count'
    | '/storefront'
    | '/users'
    | '/vendors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/'
    | '/customer-display'
    | '/locations'
    | '/login'
    | '/barcode'
    | '/deliveries'
    | '/inventory'
    | '/layaway'
    | '/pos'
    | '/register'
    | '/sales'
    | '/shifts'
    | '/ai-insights'
    | '/analytics'
    | '/audit-log'
    | '/backup'
    | '/branches'
    | '/bundles'
    | '/categories'
    | '/customers'
    | '/distributors'
    | '/expenses'
    | '/exports'
    | '/feedback'
    | '/gift-cards'
    | '/online-orders'
    | '/promotions'
    | '/purchase-orders'
    | '/report-builder'
    | '/segments'
    | '/settings'
    | '/smart-pricing'
    | '/stock-count'
    | '/storefront'
    | '/users'
    | '/vendors'
  id:
    | '__root__'
    | '/$'
    | '/_authenticated'
    | '/customer-display'
    | '/locations'
    | '/login'
    | '/_authenticated/_admin'
    | '/_authenticated/barcode'
    | '/_authenticated/deliveries'
    | '/_authenticated/inventory'
    | '/_authenticated/layaway'
    | '/_authenticated/pos'
    | '/_authenticated/register'
    | '/_authenticated/sales'
    | '/_authenticated/shifts'
    | '/_authenticated/_admin/ai-insights'
    | '/_authenticated/_admin/analytics'
    | '/_authenticated/_admin/audit-log'
    | '/_authenticated/_admin/backup'
    | '/_authenticated/_admin/branches'
    | '/_authenticated/_admin/bundles'
    | '/_authenticated/_admin/categories'
    | '/_authenticated/_admin/customers'
    | '/_authenticated/_admin/distributors'
    | '/_authenticated/_admin/expenses'
    | '/_authenticated/_admin/exports'
    | '/_authenticated/_admin/feedback'
    | '/_authenticated/_admin/gift-cards'
    | '/_authenticated/_admin/online-orders'
    | '/_authenticated/_admin/promotions'
    | '/_authenticated/_admin/purchase-orders'
    | '/_authenticated/_admin/report-builder'
    | '/_authenticated/_admin/segments'
    | '/_authenticated/_admin/settings'
    | '/_authenticated/_admin/smart-pricing'
    | '/_authenticated/_admin/stock-count'
    | '/_authenticated/_admin/storefront'
    | '/_authenticated/_admin/users'
    | '/_authenticated/_admin/vendors'
    | '/_authenticated/_admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CustomerDisplayRoute: typeof CustomerDisplayRoute
  LocationsRoute: typeof LocationsRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-display': {
      id: '/customer-display'
      path: '/customer-display'
      fullPath: '/customer-display'
      preLoaderRoute: typeof CustomerDisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/barcode': {
      id: '/_authenticated/barcode'
      path: '/barcode'
      fullPath: '/barcode'
      preLoaderRoute: typeof AuthenticatedBarcodeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/deliveries': {
      id: '/_authenticated/deliveries'
      path: '/deliveries'
      fullPath: '/deliveries'
      preLoaderRoute: typeof AuthenticatedDeliveriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/layaway': {
      id: '/_authenticated/layaway'
      path: '/layaway'
      fullPath: '/layaway'
      preLoaderRoute: typeof AuthenticatedLayawayRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pos': {
      id: '/_authenticated/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AuthenticatedPosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/register': {
      id: '/_authenticated/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthenticatedRegisterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shifts': {
      id: '/_authenticated/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof AuthenticatedShiftsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin/': {
      id: '/_authenticated/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/ai-insights': {
      id: '/_authenticated/_admin/ai-insights'
      path: '/ai-insights'
      fullPath: '/ai-insights'
      preLoaderRoute: typeof AuthenticatedAdminAiInsightsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/analytics': {
      id: '/_authenticated/_admin/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/audit-log': {
      id: '/_authenticated/_admin/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuthenticatedAdminAuditLogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/backup': {
      id: '/_authenticated/_admin/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof AuthenticatedAdminBackupRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/branches': {
      id: '/_authenticated/_admin/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof AuthenticatedAdminBranchesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/bundles': {
      id: '/_authenticated/_admin/bundles'
      path: '/bundles'
      fullPath: '/bundles'
      preLoaderRoute: typeof AuthenticatedAdminBundlesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/categories': {
      id: '/_authenticated/_admin/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/customers': {
      id: '/_authenticated/_admin/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/distributors': {
      id: '/_authenticated/_admin/distributors'
      path: '/distributors'
      fullPath: '/distributors'
      preLoaderRoute: typeof AuthenticatedAdminDistributorsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/expenses': {
      id: '/_authenticated/_admin/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedAdminExpensesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/exports': {
      id: '/_authenticated/_admin/exports'
      path: '/exports'
      fullPath: '/exports'
      preLoaderRoute: typeof AuthenticatedAdminExportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/feedback': {
      id: '/_authenticated/_admin/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AuthenticatedAdminFeedbackRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/gift-cards': {
      id: '/_authenticated/_admin/gift-cards'
      path: '/gift-cards'
      fullPath: '/gift-cards'
      preLoaderRoute: typeof AuthenticatedAdminGiftCardsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/online-orders': {
      id: '/_authenticated/_admin/online-orders'
      path: '/online-orders'
      fullPath: '/online-orders'
      preLoaderRoute: typeof AuthenticatedAdminOnlineOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/promotions': {
      id: '/_authenticated/_admin/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof AuthenticatedAdminPromotionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/purchase-orders': {
      id: '/_authenticated/_admin/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof AuthenticatedAdminPurchaseOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/report-builder': {
      id: '/_authenticated/_admin/report-builder'
      path: '/report-builder'
      fullPath: '/report-builder'
      preLoaderRoute: typeof AuthenticatedAdminReportBuilderRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/segments': {
      id: '/_authenticated/_admin/segments'
      path: '/segments'
      fullPath: '/segments'
      preLoaderRoute: typeof AuthenticatedAdminSegmentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/settings': {
      id: '/_authenticated/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/smart-pricing': {
      id: '/_authenticated/_admin/smart-pricing'
      path: '/smart-pricing'
      fullPath: '/smart-pricing'
      preLoaderRoute: typeof AuthenticatedAdminSmartPricingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/stock-count': {
      id: '/_authenticated/_admin/stock-count'
      path: '/stock-count'
      fullPath: '/stock-count'
      preLoaderRoute: typeof AuthenticatedAdminStockCountRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/storefront': {
      id: '/_authenticated/_admin/storefront'
      path: '/storefront'
      fullPath: '/storefront'
      preLoaderRoute: typeof AuthenticatedAdminStorefrontRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/users': {
      id: '/_authenticated/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/vendors': {
      id: '/_authenticated/_admin/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof AuthenticatedAdminVendorsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAiInsightsRoute: typeof AuthenticatedAdminAiInsightsRoute
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminAuditLogRoute: typeof AuthenticatedAdminAuditLogRoute
  AuthenticatedAdminBackupRoute: typeof AuthenticatedAdminBackupRoute
  AuthenticatedAdminBranchesRoute: typeof AuthenticatedAdminBranchesRoute
  AuthenticatedAdminBundlesRoute: typeof AuthenticatedAdminBundlesRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminCustomersRoute: typeof AuthenticatedAdminCustomersRoute
  AuthenticatedAdminDistributorsRoute: typeof AuthenticatedAdminDistributorsRoute
  AuthenticatedAdminExpensesRoute: typeof AuthenticatedAdminExpensesRoute
  AuthenticatedAdminExportsRoute: typeof AuthenticatedAdminExportsRoute
  AuthenticatedAdminFeedbackRoute: typeof AuthenticatedAdminFeedbackRoute
  AuthenticatedAdminGiftCardsRoute: typeof AuthenticatedAdminGiftCardsRoute
  AuthenticatedAdminOnlineOrdersRoute: typeof AuthenticatedAdminOnlineOrdersRoute
  AuthenticatedAdminPromotionsRoute: typeof AuthenticatedAdminPromotionsRoute
  AuthenticatedAdminPurchaseOrdersRoute: typeof AuthenticatedAdminPurchaseOrdersRoute
  AuthenticatedAdminReportBuilderRoute: typeof AuthenticatedAdminReportBuilderRoute
  AuthenticatedAdminSegmentsRoute: typeof AuthenticatedAdminSegmentsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSmartPricingRoute: typeof AuthenticatedAdminSmartPricingRoute
  AuthenticatedAdminStockCountRoute: typeof AuthenticatedAdminStockCountRoute
  AuthenticatedAdminStorefrontRoute: typeof AuthenticatedAdminStorefrontRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminVendorsRoute: typeof AuthenticatedAdminVendorsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAiInsightsRoute: AuthenticatedAdminAiInsightsRoute,
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminAuditLogRoute: AuthenticatedAdminAuditLogRoute,
  AuthenticatedAdminBackupRoute: AuthenticatedAdminBackupRoute,
  AuthenticatedAdminBranchesRoute: AuthenticatedAdminBranchesRoute,
  AuthenticatedAdminBundlesRoute: AuthenticatedAdminBundlesRoute,
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
  AuthenticatedAdminCustomersRoute: AuthenticatedAdminCustomersRoute,
  AuthenticatedAdminDistributorsRoute: AuthenticatedAdminDistributorsRoute,
  AuthenticatedAdminExpensesRoute: AuthenticatedAdminExpensesRoute,
  AuthenticatedAdminExportsRoute: AuthenticatedAdminExportsRoute,
  AuthenticatedAdminFeedbackRoute: AuthenticatedAdminFeedbackRoute,
  AuthenticatedAdminGiftCardsRoute: AuthenticatedAdminGiftCardsRoute,
  AuthenticatedAdminOnlineOrdersRoute: AuthenticatedAdminOnlineOrdersRoute,
  AuthenticatedAdminPromotionsRoute: AuthenticatedAdminPromotionsRoute,
  AuthenticatedAdminPurchaseOrdersRoute: AuthenticatedAdminPurchaseOrdersRoute,
  AuthenticatedAdminReportBuilderRoute: AuthenticatedAdminReportBuilderRoute,
  AuthenticatedAdminSegmentsRoute: AuthenticatedAdminSegmentsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminSmartPricingRoute: AuthenticatedAdminSmartPricingRoute,
  AuthenticatedAdminStockCountRoute: AuthenticatedAdminStockCountRoute,
  AuthenticatedAdminStorefrontRoute: AuthenticatedAdminStorefrontRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminVendorsRoute: AuthenticatedAdminVendorsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedBarcodeRoute: typeof AuthenticatedBarcodeRoute
  AuthenticatedDeliveriesRoute: typeof AuthenticatedDeliveriesRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedLayawayRoute: typeof AuthenticatedLayawayRoute
  AuthenticatedPosRoute: typeof AuthenticatedPosRoute
  AuthenticatedRegisterRoute: typeof AuthenticatedRegisterRoute
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRoute
  AuthenticatedShiftsRoute: typeof AuthenticatedShiftsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedBarcodeRoute: AuthenticatedBarcodeRoute,
  AuthenticatedDeliveriesRoute: AuthenticatedDeliveriesRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedLayawayRoute: AuthenticatedLayawayRoute,
  AuthenticatedPosRoute: AuthenticatedPosRoute,
  AuthenticatedRegisterRoute: AuthenticatedRegisterRoute,
  AuthenticatedSalesRoute: AuthenticatedSalesRoute,
  AuthenticatedShiftsRoute: AuthenticatedShiftsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CustomerDisplayRoute: CustomerDisplayRoute,
  LocationsRoute: LocationsRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
